# This workflow is used as a CI action upon creating a new PR.
# It runs tests, checks code formatting, performs static analysis, 
# and ensures the project compiles without warnings.

name: Work Hive CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.1-otp-27'
          otp-version: '27'
          
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
          
      - name: Install dependencies
        run: mix deps.get

      - name: Compile the project
        run: mix compile --warnings-as-errors

      - name: Check code formatting
        run: mix format --check-formatted

      - name: Run credo (Static Code Analysis)
        run: mix credo --strict

      - name: Run Dialyzer (Type Checking)
        run: mix dialyzer
        
      - name: Run tests
        run: mix test
