# This workflow is triggered upon the pushing of a new commit or merging a branch to the main branch.
# The workflow includes the following steps:
# 1. build: Builds the Docker image and pushes it to Docker Hub.
# 2. deploy: Pulls the Docker image from Docker Hub and deploys it to the server via SSH.

name: Work Hive Release Prod CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Image Tag
        id: vars
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            dxinn/work-hive:${{ env.IMAGE_TAG }}
            dxinn/work-hive:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull dxinn/work-hive:${{ env.IMAGE_TAG }}
            docker stop work-hive || true
            docker rm work-hive || true
            docker run -d --name work-hive -e SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} -p 4000:4000 dxinn/work-hive:${{ env.IMAGE_TAG }}